- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
- name: start apache service
  tags: apache,apache2,ubuntu
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
# - name: install apache on Ubuntu servers
#   tags: apache,apache2,ubuntu
#   apt:
#     name: "{{ apache_package_name }}"
#     state: latest
#   when: ansible_distribution == "Ubuntu"


# - name: change email adress for amazon.aws.rds_instance
#   tags: apache,httpd,ubuntu
#   lineinfile:



- name: Copy default html file for site
  tags: apache,ubuntu,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644