- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache on Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu"


# - name: change email adress for amazon.aws.rds_instance
#   tags: apache,httpd,ubuntu
#   lineinfile:



- name: cop default html file for site
  tags: apache,ubuntu,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644